### PR TITLE
Fix utf8 decode

### PR DESCRIPTION
**Pull request by zunda-pixel**
## Summary

replace to String(decoding:as) from String(data:encoding)

## Dependencies

None

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran the `./bin/test` script and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Comment by zunda-pixel** [comment]
can you review? @QuietMisdreavus

**Review by QuietMisdreavus — APPROVED** [review]
This looks good, thanks! Just one more rebase and this should be good to go.

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by zunda-pixel** [comment]
thank you for reviewing! @QuietMisdreavus 
I rebased

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Pull request merged**
