### PR TITLE
Revert "Bump Swift version"

### PR DESCRIPTION
**Pull request by franklinsch**
Unfortunately we need to revert this temporarily to investigate an issue with the Swift toolchain build.

Reverts apple/swift-markdown#4

### CODE REVIEW

**Comment by franklinsch** [comment]
@swift-ci please test

**Review by ethan-kusters — APPROVED** [review]

**Comment by franklinsch** [comment]
@swift-ci please test

**Comment by franklinsch** [comment]
@Kyle-Ye Sorry I had to revert this PR for now—we were landing integration of Swift-DocC in the Swift toolchain at the same time (https://github.com/apple/swift/pull/39723). Do you mind creating a PR with your changes today so that we can test them in the toolchain build?

**Comment by Kyle-Ye** [comment]
> @Kyle-Ye Sorry I had to revert this PR for now—we were landing integration of Swift-DocC in the Swift toolchain at the same time ([apple/swift#39723](https://github.com/apple/swift/pull/39723)). Do you mind creating a PR with your changes today so that we can test them in the toolchain build?

Got it.

**Pull request merged**
