### PR TITLE
Fix typo loacation to location.

### PR DESCRIPTION
**Pull request by Iikeli**
## Summary

Noticed that there was a typo on a file name, and the test class it contained. This PR fixes that typo.

## Dependencies

None

## Testing

Check that the typo is fixed correctly.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran the `./bin/test` script and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Review by Kyle-Ye — APPROVED** [review]

**Comment by Iikeli** [comment]
@swift-ci Please test

**Comment by Kyle-Ye** [comment]
@swift-ci please test

**Comment by Iikeli** [comment]
@swift-ci please test

**Comment by Kyle-Ye** [comment]
> Rebased.

Seems like you are doing "merge" instead of "rebase".

**Comment by Iikeli** [comment]
Ah yes, always forget that the GitHub button merges instead of rebases. Sorry about that. Would you like me to revert and rebase instead?

**Comment by Kyle-Ye** [comment]
> Ah yes, always forget that the GitHub button merges instead of rebases. Sorry about that. Would you like me to revert and rebase instead?

You can rebase "origin:main" into your local branch-"fix-location-typo" and then force push it to "fork:fix-location-typo". (Assuming you config git@github.com:apple/swift-markdown.git as "origin" and git@github.Iikeli/swift-markdown.git as "fork")

I can't do that for you since I don't have write access to your repo(git@github.Iikeli/swift-markdown.git).

**Comment by Iikeli** [comment]
I'll keep that in mind. Thanks.
If it doesn't matter to you, then I'll leave it as is.

**Comment by Kyle-Ye** [comment]
@swift-ci please test

**Pull request merged**
