### PR TITLE
Add support for Doxygen discussion/note tags

### PR DESCRIPTION
**Pull request by j-f1**
Bug/issue #, if applicable: Related to rdar://116077012

## Summary

This PR adds support for parsing the Doxygen `@discussion` and `@note` tags. See also: https://github.com/apple/swift-docc/pull/798

## Dependencies

None; the PR to `swift-docc` depends on this PR.

## Testing

I’ve added basic automated tests, but am open to adding more!

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran the `./bin/test` script and it succeeded
- [ ] Updated documentation if necessary — Is there documentation for all the node types?

### CODE REVIEW

**Comment by j-f1** [comment]
@swift-ci please test

**Comment by Kyle-Ye** [comment]
>   * The “Checking license headers” check failed but I don’t understand why. It looks like my headers are well-formed? It wants me to change them to say “Copyright (c) YEARS”

This issue should be fixed by #160. After it gets merged, you can rebase/merge main to give it a try.

**Comment by Kyle-Ye** [comment]
I remember we used to check `./bin/test` result on CI. But it does not now.

It means we can merge PR when `./bin/test` result fails.

cc @franklinsch  @shahmishal

**Comment by Kyle-Ye** [comment]
GitHub accidentally closes this after #160 gets merged. Reopened it. Sorry for the inconvenience.

**Review by Kyle-Ye — CHANGES_REQUESTED** [review]
IMO, you need to update the CMakeLists.txt file to add the files explicitly.

https://github.com/apple/swift-markdown/blob/main/Sources/Markdown/CMakeLists.txt

See discussion about file lists and folder blob here https://github.com/apple/swift-markdown/pull/141#discussion_r1373245004

Also what will happen if someone accidentally forgot to update the CMakeLists.txt file? Should we add a CI to check this? cc @compnerd

**Comment by j-f1** [comment]
@swift-ci please test

**Review by Kyle-Ye — APPROVED** [review]

**Comment by j-f1** [comment]
@swift-ci please test

**Pull request merged**
