### PR TITLE
Revert "revert" to test toolchain change

### PR DESCRIPTION
**Pull request by Kyle-Ye**
- Revert "Revert "Fix deprecated launch and launchPath API on Process""
- Revert "Revert "Fix deprecated readDataToEndOfFile API""
- Revert "Revert "Bump Swift version (#4)" (#11)"

Bug/issue #, if applicable: 

## Summary

Revert #11 and #12 to test the change in the toolchain build.
@franklinsch 

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Ran the `./bin/test` script and it succeeded

### CODE REVIEW

**Comment by franklinsch** [comment]
Tracking testing this alongside Swift here: https://github.com/apple/swift/pull/40031

**Comment by Kyle-Ye** [comment]
Could you please run test on this repo so that we can merge it after the test on swift success? @franklinsch

**Comment by franklinsch** [comment]
Now that the smoke tests pass, I also triggered toolchain builds in that PR.

@swift-ci please test

**Comment by Kyle-Ye** [comment]
> Now that the smoke tests pass, I also triggered toolchain builds in that PR.
> 
> @swift-ci please test

Seems like both smoke tests and toolchain builds are passed. Could you review the change and merge it?

**Comment by Kyle-Ye** [comment]
@franklinsch Could we run test again and merge it?

**Comment by ethan-kusters** [comment]
@swift-ci Please test

**Review by QuietMisdreavus — APPROVED** [review]
It looks like the Swift toolchains built just fine with this PR, so let's go ahead and (re-)land it!

**Pull request merged**
