### PR TITLE
Fix/remove argument-parser

### PR DESCRIPTION
**Pull request by griffin-stewie**
## Summary

Remove the executable "markdown-tool" from the product so that ArgumentParser is not added unnecessarily when used it as a library.

In my case, I added swift-markdown to my CLI tool that it uses swift-argument-parser v1.0.1  then I got the following error.

```
Dependencies could not be resolved because root depends on 'swift-argument-parser' 0.4.4..<0.5.0 and root depends on 'swift-argument-parser' 1.0.0..<1.1.0.
```

This PR will fix this issue.

## Dependencies

none.

## Testing

All tests passed my local environment.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
    - I don’t think we need to add tests for this PR. 
- [x] Ran the `./bin/test` script and it succeeded
    -  added Package*.swift as exceptions
- [x] Updated documentation if necessary
    - I don’t think we need to add tests for this PR.

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
Thanks for this! It looks like this shared some overlap with https://github.com/apple/swift-markdown/pull/13 - would you mind reworking this on top of the current `main` branch?

**Comment by griffin-stewie** [comment]
@QuietMisdreavus 
Thank you for reviewing my pull request.

I went over the current status of the main branch and what we wanted to do. Many of the changes I added were already included in the main branch, so they turned out to be simple changes.

Please review this pull request.

**Comment by ethan-kusters** [comment]
@swift-ci please test

**Comment by griffin-stewie** [comment]
@ethan-kusters 
Thank you for reviewing, I have made the same fix to Package.swift as Package@swift-5.5.swift.

**Comment by ethan-kusters** [comment]
@swift-ci please test

**Review by ethan-kusters — APPROVED** [review]
Looks great. Thank you so much @griffin-stewie!

**Pull request merged**
