### PR TITLE
Bump Swift version

### PR DESCRIPTION
**Pull request by Kyle-Ye**
## Summary

Bump the Swift version Package.swift use to 5.4. And add a new 5.5 Package.swift file

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Ran the `./bin/test` script and it succeeded

### CODE REVIEW

**Comment by Kyle-Ye** [comment]
cc @franklinsch

**Comment by franklinsch** [comment]
Thanks for investigating these options! I think updating to 5.3 is reasonable (option 2) since it was released more than a year ago.

**Comment by Kyle-Ye** [comment]
> Thanks for investigating these options! I think updating to 5.3 is reasonable (option 2) since it was released more than a year ago.

Done. Could you please help me run test on this?

**Comment by franklinsch** [comment]
@swift-ci please test this

**Comment by Kyle-Ye** [comment]
> @swift-ci please test this

Looks like it does not trigger the Test check. Maybe it should be "@swift-ci please test"?

**Comment by franklinsch** [comment]
@swift-ci please test

**Comment by franklinsch** [comment]
> > @swift-ci please test this
> 
> Looks like it does not trigger the Test check. Maybe it should be "@swift-ci please test"?

Yes, just noticed this as well 😄

**Comment by Kyle-Ye** [comment]
Any other suggestion on this? Or could we merge it with your approval?

**Comment by franklinsch** [comment]
Looking at the CI logs, it looks like it's now emitting this warning:

> FormatCommand.swift:133:19: note: use 'run' instead

Can we resolve this before merging this PR?

**Comment by franklinsch** [comment]
Actually, I see that warning happened before the changes of this PR, so we can resolve this as part of another PR.

**Review by franklinsch — APPROVED** [review]
Thanks @Kyle-Ye for another awesome PR! 🙌

**Comment by Kyle-Ye** [comment]
> Looking at the CI logs, it looks like it's now emitting this warning:
> 
> > FormatCommand.swift:133:19: note: use 'run' instead
> 
> Can we resolve this before merging this PR?

It seems to be fixed by this PR.(Which is blocked by this PR before)

**Pull request merged**
