### PR TITLE
Fix existential any

### PR DESCRIPTION
**Pull request by zunda-pixel**
## Summary

support `existential any` [SE-0335](https://forums.swift.org/t/se-0335-introduce-existential-any/53934) for Swift 6.0

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran the `./bin/test` script and it succeeded
- [x] Updated documentation if necessary

### CODE REVIEW

**Comment by Kyle-Ye** [comment]
The any keyword was introduced in Swift 5.6.

Before we bump the minimal supported Swift version ([this PR](https://github.com/apple/swift-markdown/pull/135) does so), I think we may have a pause on this.

**Comment by zunda-pixel** [comment]
Updating to Swift 5.6 has no problem?

**Comment by Kyle-Ye** [comment]
> Updating to Swift 5.6 has no problem?

https://forums.swift.org/t/documentation-workgroup-meeting-july-17th-2023/66170/3

**Comment by zunda-pixel** [comment]
thanks, I see

**Comment by zunda-pixel** [comment]
I add `Package@swift-5.6.swift` to support Swift 5.6

**Pull request closed without merging**
