### PR TITLE
[5.10] Add link title support for commonmark

### PR DESCRIPTION
**Pull request by Kyle-Ye**
Cherry-pick of #140

- **Explanation**: Add link title support for commonmark and update the initial behavior for image title.
- **Scope**: Small additive feature for swift-markdown.
- **Issue**: #67
- **Risk**: Low. 
- **Testing**: Added test in LinkTests to verify the new feature and update test case for image markdown output.
- **Reviewer**: @QuietMisdreavus

### CODE REVIEW

**Comment by Kyle-Ye** [comment]
@swift-ci please test

**Comment by QuietMisdreavus** [comment]
Is there a corresponding Swift-DocC change to port the test fixes from https://github.com/apple/swift-docc/pull/708?

**Comment by Kyle-Ye** [comment]
> Is there a corresponding Swift-DocC change to port the test fixes from [apple/swift-docc#708](https://github.com/apple/swift-docc/pull/708)?

Sure. I'll add it now.

**Comment by Kyle-Ye** [comment]
The swift-docc PR is here https://github.com/apple/swift-docc/pull/709 cc @QuietMisdreavus 

And we need to merge this PR first.

According to the complete process, we need to create an empty PR in the swift repository and pass the cross-repo test before merge. Considering the low risk here, I think we can just skip it. Also considering the release/5.10 branch is just cut off and is actually identical to main before my PR is merged.

**Review by QuietMisdreavus — APPROVED** [review]
Please coordinate with @franklinsch to make sure that the Swift-DocC PR can land immediately after this one.

**Pull request merged**
